name: Release

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Helm Chart Package
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm package ./web-echo-app/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-echo-app-0.1.0
          path: web-echo-app-0.1.0.tgz

      - name: Make Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            web-echo-app-0.1.0.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}