name: Release

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm package ./web-echo-app/

      - name: Run a one-line script
        run: ls -la
